version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/" # location of package.json
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "some-package"
        versions: ["1.x.x"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/" # location of Dockerfile
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"
